version: 1.0
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:21.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SO:ME:FIN:G:ER:PR:IN:T"
      - checkout
      - run: mvn clean install
      - run: mvn test